use std::path::Path;
use std::sync::{LazyLock, RwLock};
use syn::{spanned::Spanned, visit::Visit};

use crate::domain::config::PolicyConfig;
use crate::domain::source::SourceFile;

static POLICY: LazyLock<RwLock<PolicyConfig>> =
    LazyLock::new(|| RwLock::new(PolicyConfig::default()));

pub(crate) fn configure(policy: &PolicyConfig) {
    *POLICY.write().expect("policy lock poisoned") = policy.clone();
}

pub(crate) fn is_test_path(path: &Path) -> bool {
    let policy = POLICY.read().expect("policy lock poisoned");
    is_test_path_with_policy(path, &policy)
}

pub(crate) fn is_test_path_with_policy(path: &Path, policy: &PolicyConfig) -> bool {
    if !policy.skip_tests {
        return false;
    }

    path.components().any(|component| {
        let component = component.as_os_str().to_string_lossy();
        policy
            .test_path_markers
            .iter()
            .any(|marker| component == marker.as_str() || component.ends_with(marker))
    })
}

pub(crate) fn is_skipped_path_with_policy(path: &Path, policy: &PolicyConfig) -> bool {
    is_test_path_with_policy(path, policy)
        || policy.skip_examples && path_has_component(path, &["examples", "example"])
        || policy.skip_benches && path_has_component(path, &["benches", "bench", "benchmarks"])
        || policy.skip_generated && path_has_component(path, &["generated", "codegen", "gen"])
}

pub(crate) fn is_skipped_source_with_policy(source: &SourceFile, policy: &PolicyConfig) -> bool {
    policy.skip_generated && source_looks_generated(&source.code)
        || policy.skip_macro_heavy_files && source_is_macro_heavy(source)
}

pub(crate) fn has_test_cfg(attrs: &[syn::Attribute]) -> bool {
    let policy = POLICY.read().expect("policy lock poisoned");
    policy.skip_tests && attrs.iter().any(attr_is_test_cfg)
}

pub(crate) fn is_dto_template_or_config_struct(item: &syn::ItemStruct) -> bool {
    let policy = POLICY.read().expect("policy lock poisoned");
    policy.skip_template_structs && has_template_attr(item)
        || policy.skip_data_carrier_structs
            && is_data_carrier_name(&item.ident.to_string(), &policy)
}

fn attr_is_test_cfg(attr: &syn::Attribute) -> bool {
    if attr.path().is_ident("test") {
        return true;
    }
    if !attr.path().is_ident("cfg") {
        return false;
    }

    attr.parse_args_with(
        syn::punctuated::Punctuated::<syn::Meta, syn::token::Comma>::parse_terminated,
    )
    .is_ok_and(|metas| {
        metas
            .iter()
            .any(|meta| cfg_without_test(meta) == Some(false))
    })
}

fn path_has_component(path: &Path, names: &[&str]) -> bool {
    path.components().any(|component| {
        let component = component.as_os_str().to_string_lossy().to_ascii_lowercase();
        names.iter().any(|name| component == *name)
    })
}

fn source_looks_generated(code: &str) -> bool {
    code.lines().take(8).any(|line| {
        let line = line.to_ascii_lowercase();
        line.contains("@generated")
            || line.contains("automatically generated")
            || line.contains("generated by")
            || line.contains("do not edit") && line.contains("generated")
    })
}

fn source_is_macro_heavy(source: &SourceFile) -> bool {
    let item_count = source.ast.items.len();
    if item_count < 3 {
        return false;
    }

    let macro_items = source
        .ast
        .items
        .iter()
        .filter(|item| matches!(item, syn::Item::Macro(_)))
        .count();

    macro_items * 2 >= item_count
}

// Three-valued evaluation with test=false. Unknown feature/platform predicates
// must not cause production-capable code to disappear.
fn cfg_without_test(meta: &syn::Meta) -> Option<bool> {
    match meta {
        syn::Meta::Path(path) if path.is_ident("test") => Some(false),
        syn::Meta::List(list) => {
            let metas = list
                .parse_args_with(
                    syn::punctuated::Punctuated::<syn::Meta, syn::token::Comma>::parse_terminated,
                )
                .ok()?;
            let values: Vec<_> = metas.iter().map(cfg_without_test).collect();
            if list.path.is_ident("not") && values.len() == 1 {
                values[0].map(|v| !v)
            } else if list.path.is_ident("all") {
                if values.contains(&Some(false)) {
                    Some(false)
                } else if values.iter().all(|v| *v == Some(true)) {
                    Some(true)
                } else {
                    None
                }
            } else if list.path.is_ident("any") {
                if values.contains(&Some(true)) {
                    Some(true)
                } else if values.iter().all(|v| *v == Some(false)) {
                    Some(false)
                } else {
                    None
                }
            } else {
                None
            }
        }
        _ => None,
    }
}

/// Mask excluded items before parsing a detector view, keeping character columns
/// and line numbers intact for diagnostics and ignore directives.
pub(crate) fn analysis_view(source: &SourceFile, policy: &PolicyConfig) -> Option<SourceFile> {
    if !policy.skip_tests {
        return None;
    }
    let mut excluded = Excluded(Vec::new());
    if source.ast.attrs.iter().any(attr_is_test_cfg) {
        excluded.0.push(source.ast.span());
    } else {
        excluded.visit_file(&source.ast);
    }
    if excluded.0.is_empty() {
        return None;
    }
    let mut chars: Vec<char> = source.code.chars().collect();
    let offset = |loc: proc_macro2::LineColumn| {
        let start: usize = source
            .code
            .split_inclusive('\n')
            .take(loc.line.saturating_sub(1))
            .map(|line| line.chars().count())
            .sum();
        start + loc.column
    };
    let mut removed_lines = std::collections::HashSet::new();
    for span in excluded.0 {
        for line in span.start().line..=span.end().line {
            removed_lines.insert(line);
        }
        for ch in &mut chars[offset(span.start())..offset(span.end())] {
            if !matches!(*ch, '\n' | '\r') {
                *ch = ' ';
            }
        }
    }
    let mut view = SourceFile::from_source(source.path.clone(), chars.into_iter().collect())
        .expect("removing cfg items preserves Rust syntax");
    let excluded_count = view
        .code
        .lines()
        .enumerate()
        .filter(|(i, line)| removed_lines.contains(&(i + 1)) && line.trim().is_empty())
        .count();
    view.line_count = source.line_count.saturating_sub(excluded_count);
    Some(view)
}

fn has_template_attr(item: &syn::ItemStruct) -> bool {
    item.attrs.iter().any(|attr| {
        attr.path().is_ident("template")
            || attr.path().is_ident("Template")
            || attr.path().is_ident("derive")
                && attr
                    .parse_args_with(
                        syn::punctuated::Punctuated::<syn::Meta, syn::token::Comma>::parse_terminated,
                    )
                    .is_ok_and(|nested| nested.iter().any(|meta| meta.path().is_ident("Template")))
    })
}

fn is_data_carrier_name(name: &str, policy: &PolicyConfig) -> bool {
    policy
        .data_carrier_struct_suffixes
        .iter()
        .any(|suffix| name.ends_with(suffix))
}

struct Excluded(Vec<proc_macro2::Span>);
impl<'a> Visit<'a> for Excluded {
    fn visit_stmt(&mut self, stmt: &'a syn::Stmt) {
        let attrs: &[syn::Attribute] = match stmt {
            syn::Stmt::Local(l) => &l.attrs,
            syn::Stmt::Expr(e, _) => expression_attrs(e),
            syn::Stmt::Macro(m) => &m.attrs,
            _ => &[],
        };
        if attrs.iter().any(attr_is_test_cfg) {
            self.0.push(stmt.span());
        } else {
            syn::visit::visit_stmt(self, stmt);
        }
    }
    fn visit_item(&mut self, item: &'a syn::Item) {
        let attrs: &[syn::Attribute] = match item {
            syn::Item::Fn(i) => &i.attrs,
            syn::Item::Mod(i) => &i.attrs,
            syn::Item::Struct(i) => &i.attrs,
            syn::Item::Enum(i) => &i.attrs,
            syn::Item::Impl(i) => &i.attrs,
            syn::Item::Trait(i) => &i.attrs,
            syn::Item::Use(i) => &i.attrs,
            syn::Item::Const(i) => &i.attrs,
            syn::Item::Static(i) => &i.attrs,
            syn::Item::Type(i) => &i.attrs,
            syn::Item::Macro(i) => &i.attrs,
            syn::Item::ForeignMod(i) => &i.attrs,
            syn::Item::Union(i) => &i.attrs,
            _ => &[],
        };
        if attrs.iter().any(attr_is_test_cfg) {
            self.0.push(item.span());
        } else {
            syn::visit::visit_item(self, item);
        }
    }
    fn visit_impl_item(&mut self, item: &'a syn::ImplItem) {
        let attrs: &[syn::Attribute] = match item {
            syn::ImplItem::Fn(i) => &i.attrs,
            syn::ImplItem::Const(i) => &i.attrs,
            syn::ImplItem::Type(i) => &i.attrs,
            _ => &[],
        };
        if attrs.iter().any(attr_is_test_cfg) {
            self.0.push(item.span());
        } else {
            syn::visit::visit_impl_item(self, item);
        }
    }
    fn visit_trait_item(&mut self, item: &'a syn::TraitItem) {
        let attrs: &[syn::Attribute] = match item {
            syn::TraitItem::Fn(i) => &i.attrs,
            syn::TraitItem::Const(i) => &i.attrs,
            syn::TraitItem::Type(i) => &i.attrs,
            _ => &[],
        };
        if attrs.iter().any(attr_is_test_cfg) {
            self.0.push(item.span());
        } else {
            syn::visit::visit_trait_item(self, item);
        }
    }
}

fn expression_attrs(e: &syn::Expr) -> &[syn::Attribute] {
    match e {
        syn::Expr::Call(e) => &e.attrs,
        syn::Expr::MethodCall(e) => &e.attrs,
        syn::Expr::Block(e) => &e.attrs,
        syn::Expr::Unsafe(e) => &e.attrs,
        syn::Expr::Async(e) => &e.attrs,
        syn::Expr::Await(e) => &e.attrs,
        syn::Expr::If(e) => &e.attrs,
        syn::Expr::Match(e) => &e.attrs,
        syn::Expr::ForLoop(e) => &e.attrs,
        syn::Expr::While(e) => &e.attrs,
        syn::Expr::Loop(e) => &e.attrs,
        syn::Expr::Macro(e) => &e.attrs,
        _ => &[],
    }
}
